# Generated by Django 5.2.4 on 2025-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stok_galon', models.IntegerField(default=0)),
            ],
        ),
    ]
